/**
 * Build-time script: serializes portfolio data from lib/data.ts
 * into netlify/functions/portfolio-context.json for the chat serverless function.
 */
import * as fs from "fs";
import * as path from "path";
import {
  siteConfig,
  stats,
  aboutParagraphs,
  experiences,
  techStack,
  proficiency,
  marqueeItems,
  projects,
  articles,
  certifications,
  education,
} from "../lib/data";

const context = {
  siteConfig,
  stats,
  aboutParagraphs,
  experiences,
  techStack,
  proficiency,
  marqueeItems,
  projects,
  articles,
  certifications,
  education,
};

const outDir = path.join(process.cwd(), "netlify", "functions");
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

const contextJson = JSON.stringify(context, null, 2);

// JSON file (for reference / local dev)
const jsonPath = path.join(outDir, "portfolio-context.json");
fs.writeFileSync(jsonPath, contextJson, "utf-8");
console.log("Wrote", jsonPath);

// TypeScript module so the Netlify function bundle includes the context at deploy time
const tsContent = `// Auto-generated by scripts/generate-portfolio-context.ts - do not edit
export const portfolioContextJson = ${JSON.stringify(contextJson)};
`;
const tsPath = path.join(outDir, "portfolio-context.generated.ts");
fs.writeFileSync(tsPath, tsContent, "utf-8");
console.log("Wrote", tsPath);
